application:    marrarmz
version:        1
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /build
          static_dir: public/build
          application_readable: true

        - url: /ckeditor
          static_dir: public/ckeditor

        - url: /ckeditorstardard
          static_dir: public/ckeditorstardard

        - url: /css
          static_dir: public/css

        - url: /expander
          static_dir: public/expander

        - url: /fonts
          static_dir: public/fonts

        - url: /img
          static_dir: public/img

        - url: /js
          static_dir: public/js

        - url: /start
          static_dir: public/start

        - url: /artisan
          script: public/index.php
          login: admin
          secure: always

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
        - ^(.*/)?\.DS_Store$

env_variables:
        GAE_SKIP_GCS_INIT: false